# Generated by Django 4.2.16 on 2024-11-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='film/', verbose_name='Заргузите картинку')),
                ('title', models.CharField(max_length=100, verbose_name='Укажите название фильма')),
                ('price', models.FloatField(verbose_name='Укажите цену')),
                ('release_date', models.DateField(verbose_name='Укажите дату выхода')),
                ('genre', models.CharField(choices=[('Ужасы', 'Ужасы'), ('Комедия', 'Комедия'), ('Боевик', 'Боевик')], default='Комедия', max_length=100, verbose_name='Укажите жанр фильма')),
                ('time', models.TimeField(verbose_name='Укажите продолжительность фильма')),
                ('director', models.CharField(max_length=100, verbose_name='Укажите имя режиссера')),
                ('trailer', models.URLField(verbose_name='Вставьте ссылку на трейлер с YouTube')),
            ],
        ),
    ]
